#! /bin/bash

NR_CPU=`nproc`
SMATCH_DIR=$(dirname $(dirname $0))
CMD=$SMATCH_DIR/smatch
API_SPECS=$SMATCH_DIR/api_spec

find -name \*.c.smatch -exec rm \{\} \;
rm -f core.*
make clean

for file in  $(ls $API_SPECS); do
	dsl_files="$dsl_files --generic-arg-file=$API_SPECS/$file"
done

find . -type f -name "*.c" | sort | uniq | rev |\
	cut -d. -f2- |\
	rev | awk " {printf \$0 ; print \".o\" } " | \
	xargs make -j${NR_CPU} -k --output-sync CHECK="$CMD -p=kernel --spammy --file-output\
		--succeed $dsl_files --wrappers --resemblance --check-api" C=1 2>&1 |\
	tee smatch.log


find -name \*.c.smatch -exec grep -F -e "Possible function not matched"\
		-e "is the only of the interface"\
		-e "Possible wrapper found" \{\} \;  >\
			smatch.warning




